// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images(image_path)
    VALUES ($1)
RETURNING
    image_id
`

func (q *Queries) CreateImage(ctx context.Context, imagePath pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, createImage, imagePath)
	var image_id int32
	err := row.Scan(&image_id)
	return image_id, err
}

const getImage = `-- name: GetImage :one
SELECT
    image_path
FROM
    images
WHERE
    image_id = $1
`

func (q *Queries) GetImage(ctx context.Context, imageID int32) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getImage, imageID)
	var image_path pgtype.Text
	err := row.Scan(&image_path)
	return image_path, err
}

const updateImage = `-- name: UpdateImage :exec
UPDATE
    images
SET
    image_path = $2
WHERE
    image_id = $1
`

type UpdateImageParams struct {
	ImageID   int32       `json:"image_id"`
	ImagePath pgtype.Text `json:"image_path"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) error {
	_, err := q.db.Exec(ctx, updateImage, arg.ImageID, arg.ImagePath)
	return err
}
