// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ImageID   int32            `json:"image_id"`
	ImagePath pgtype.Text      `json:"image_path"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Record struct {
	RecordID    int32            `json:"record_id"`
	ImageID     int32            `json:"image_id"`
	SightID     pgtype.Int4      `json:"sight_id"`
	SightName   pgtype.Text      `json:"sight_name"`
	Copywriting string           `json:"copywriting"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Sight struct {
	SightID          int32            `json:"sight_id"`
	SightName        string           `json:"sight_name"`
	SightDescription string           `json:"sight_description"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}
