services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/config.json
    volumes:
      # Mounts the storage directory to the container
      # - ../storage:/app/storage
      - ../config.json:/app/config.json
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gzic_walk
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # Mounts test SQL script for initializing test data
      # - ./database/test.sql:/docker-entrypoint-initdb.d/test.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: